---
- name: First Play - Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansible/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/ansible
    - name : Build Docker Image
      command: docker build -t wudixo/contactui .
    - name : Push Docker Image
      command: docker push wudixo/contactui
- name: Second Play - K8S Deployment
  hosts: kubernetes
  tasks:
   - name: Copy K8S Manifest yml
     copy:
       src: contact_ui_deployment.yml
       dest: /home/ansible
   - name : K8S Deployment
     command: kubectl apply -f contact_ui_deployment.yml
